### ISSUE TITLE
Can't Open the Download Link

### ISSUE THREAD

**Issue by agjayant** [erichuang0771/PoseBox-Reid#1]
The link doesn't seem to work: http://www.visualsolver.com:6008/

**Comment by agjayant** [comment]
Hi @erichuang0771, 
I wanted to work on this code. Can you please help with the download link ?

**Comment by buaaswf** [comment]
Dear author, we cannot open the download link, please help us.

**Comment by erichuang0771** [comment]
Hi All, sincerely apologize about the breakdown. Our server was experiencing hard time supporting web services and multiple GPU training tasks  :) . Please feel free to use our back up server: http://www.visualsolver.xyz:8080/
